mod state;

pub use state::StateLifeCycle;
pub use state::StateManagement;

pub struct Task {
    id: Option<i32>, // optional ID, generated by database
    pub title: String,
    description: Option<String>, // optional String
    state_management: Option<StateManagement>,
    state_lyfecycle: Option<StateLifeCycle>, 
    creation_date: Option<String>, // TO DO: date type
    expiration_date: Option<String> // TO DO: date type
}

impl Task {

    // to create a default task 
    pub fn create_task() -> Task {
        Task{
            id: None,
            title: String::from("Empty Task"),
            description: None,
            state_management: None,
            state_lyfecycle: None,
            creation_date: None,
            expiration_date: None
        }

    
    }
}

